image: node:14.17.0

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - yarn install
              - yarn test
    - step:
        name: Build Storybook
        script:
          - yarn build-storybook
        caches:
          - node
    - step:
        size: 2x
        name: Publish Storybook
        caches:
          - node
        script:
          - unset CI
          - pipe: atlassian/firebase-deploy:0.3.4
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT_ID
              MESSAGE: 'deploying to loplat UI'
              DEBUG: 'false'
          - export COMMIT_MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
          - echo COMMIT_MESSAGE
          - curl -X POST -H "Content-type:application/json" --data "{
              \"text\":\"스토리북이 업데이트 되었습니다. https://loplat-ui.web.app/  \n\n*개발자 커밋메시지* $COMMIT_MESSAGE\"
            }" https://hooks.slack.com/services/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
